twig:
    file_name_pattern: '*.twig'
    globals:
        app_name: '%app_name%'
        app_description: '%app_description%'
        app_version: '%app_version%'
        app_currency: '%app_currency%'
        app_currency_symbol: '%app_currency_symbol%'
        app_uploads_dir: '%app_uploads_dir%'
        stripe_public_key: '%stripe_public_key%'
        twigPages: '@App\Repository\PageRepository'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
